### ISSUE TITLE
Score update problem

### ISSUE THREAD

**Issue by goncalogato** [openmusic-project/openmusic#64]
Hello,

When you change a score object by going inside and edit, it does not display the change when you close it. It does update when you click m two times (thus hiding and showing the content again). This can slow down visualisation inside OM.

thanks
g

**Comment by karimhaddad** [comment]
Dear G

Sorry but i am not sure to understand you well here:

1) which OS are you using
2) Is the patch 171224 installed?

When you say going inside and edit you mean changing notes? and then close it?
Can you be more precise?

Thank you

Best
K

**Comment by karimhaddad** [comment]
Dear Goncalo, 

Ok i could see the problem. It is macosx related. I have fixed it and will issue a new patch tomorrow.
 But if you are in a hurry, you can copy paste this code at the end of the last patch i've put onlune:


```
(defmethod move-selection ((self scorePanel) dir)

  (loop for item in (selection? self) do
          (score-move-a item self (cond
                                   (#+(or cocoa win32)(om-option-key-p)
                                    #+linux(om-option-key-p) 
                                    (if (= dir 0) 700 -700))
                                   ((om-shift-key-p) (if (= dir 0) 1200 -1200))
                                   (t (let ((factor (round (approx-factor (get-current-scale (staff-tone self))))))
                                        (if (= dir 0) factor
                                          (* -1 factor)))))))
  #+(or linux win32)(update-panel self t)
  #+macosx(unless (in-page-mode? self)
            (update-alt-panel self)
            )
  #+macosx(update-slot-edit self)
  (om-invalidate-view self)
    #+macosx(progn
            (change-edit-mode (car (frames (associated-box (object (editor self))))))
            (change-edit-mode (car (frames (associated-box (object (editor self)))))))
    )
```

Best
K

**Comment by goncalogato** [comment]
Thanks so much.

**Comment by karimhaddad** [comment]
Now the patch is available.

Best
K

**Comment by goncalogato** [comment]
Arrow issue seems to happen only with the NOTE objetc.

**Comment by karimhaddad** [comment]
Dear Goncalogato,

Please can you be more specific here?

1) Can you provide the popup window of the error message, and confirm that this happens ONLY in the NOTE object?
It is not clear to me.

2) The SDIFFILE and the chord-seq-analysis is a completely different issue. Can you open a new ticket for that, and please try to be more specific. If the analysis fails, it could be either, you are  using an old version of the OM-pm2 library, or an old version of pm2 binary, etc...

Best
K

**Comment by goncalogato** [comment]
Yes, sure. Here is the error I get while editing NOTE with arrows:

<img width="264" alt="image" src="https://github.com/user-attachments/assets/b4b86504-c161-45cf-b4f8-af510a67d875" />

It does not happen with CHORD, CHORD-SEQ, VOICE and POLY (tried with the default one voice).

PS: I will open another ticket for the pm2.

Thanks,
G

**Comment by karimhaddad** [comment]
Dear G, 

Thank you again. Your feedback is really appreciated. 
You just found a bug which is fixed (cf. the new patch available in the release section).
And please feel free to report any other issue you may find.

Best Regards
Karim

**Comment by goncalogato** [comment]
Dear K,

With the latest patch_191224.lisp I still get the error message in NOTE, while using the arrows inside. Thank you

**Comment by karimhaddad** [comment]
Yes you're right.
and sorry didn't understand that it was the NOTE editor. Got mixed up with the internal editor of chord-seq.
Will issue a new patch.

Best
K

**Comment by goncalogato** [comment]
This is now working correctly. Thank you so much. Best
